---
- name: Run AAP installation
  include_role:
    name: infra.aap_utilities.aap_setup_install
  vars:
    aap_setup_inst_containerized: "{{ aap_setup_inst_containerized }}"
    aap_setup_inst_force: "{{ aap_setup_inst_force }}"
    aap_setup_inst_inventory: "{{ aap_setup_inst_inventory }}"
    aap_setup_inst_extra_vars: "{{ aap_setup_inst_extra_vars }}"
    aap_setup_inst_extra_vars_files: "{{ aap_setup_inst_extra_vars_files }}"
